

def test_error(request):
    raise Exception("Error de prueba para CloudWatch y logging de Django")
